# Generated by Django 5.1.1 on 2024-09-19 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('Cognitive', 'Cognitive Status'), ('Physical', 'Physical Exam')], max_length=50)),
                ('assessment_date', models.DateField()),
                ('questions_and_answers', models.JSONField()),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.patient')),
            ],
        ),
    ]
