# Generated by Django 5.1.1 on 2024-09-19 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_assessment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assessment',
            table='assessment_table',
        ),
    ]
