# Generated by Django 5.1.1 on 2024-09-20 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_remove_assessment_patient_assessment_patients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='patients',
        ),
        migrations.AddField(
            model_name='assessment',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapi.patient'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('cognitive', 'Cognitive Status'), ('physical', 'Physical Health')], max_length=50),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='final_score',
            field=models.FloatField(),
        ),
    ]
